language: java
jdk:
  - openjdk11.0.9
  - openjdk12
  - openjdk13
  - openjdk14
  - openjdk15
  - openjdk-ea

addons:
  sonarcloud:
    organization: "nhenneaux"
    token:
      secure: "K7XrobiWi+cBNzbp4hXj5kUKtmPtg1EhnXX6a/l7NG/oTH5yIiGMpOIiAsHNW18GnHbUK9o341d6kvF6S+I9dptP7CULc2Ukk8vnMNeRLB+hO5zEde3XQ5cjWPLsuVnS3N7aPVHaOiwAGsbqvz+9VVQHy1A9HFwPyjzLHf9g3vmzyNQQdpjNJ6zpNKnvezU9U/iH0QOiYZZKc7nxRpESbYdW3ONDAQ5VWsWqqVwm7SGfmYMOkokUfyI75Mc1hFKG5nwtxLNVc7aXgika3x71LMfNuU0LpbWe6eJaTi1kVTia+hFWBZMhNAzd3QAdBmGtULp1I2McfZ97S/PKoOtS/7j8FFYFlw8jvvea0pPx8vJrOYST+/Bj8ZJpftj7lowmzFtGt4OvtIFcwGDed9Vfen5HilCgxz0gXtCIyDm3ZiDHdX2tPEq57SsL5QcvfmVLf4m8w5KTeYYV9yC0mIa+jka7xo3cHFjwokbAvP2ah6xv+Ga4lAdKLDeP+Z4tJAnQFxur+ZM3PF2tSzon+MoViv68jsEYFrhSz2a2NQe5gwMoGYhSjbvpnGpiyjalPhif37BO6CTHYOoYuSB9wIDKIE0pQGX5JHkQivc1QSmklw+SNfq9c3P88zHMuvfNc9SqIkVYb+GJzmecCozF3OKlnBUdzj2Y9IiaT0KPOpSLE/U="


script: mvn -B -C verify sonar:sonar -Dsonar.projectKey=nhenneaux_jersey-httpclient-connector
