language: java

before_script:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

jobs:
  include:

    - stage: 🍺 adoptopenjdk.net - HotSpot
      env: JDK=11 + Hotspot
      script: source install-jdk.sh --url 'https://api.adoptopenjdk.net/v2/binary/releases/openjdk11?openjdk_impl=hotspot&os=linux&arch=x64&release=latest&heap_size=normal&type=jdk'
    - # stage: ...
      env: JDK=15 + Hotspot
      script: source install-jdk.sh --url 'https://api.adoptopenjdk.net/v2/binary/releases/openjdk15?openjdk_impl=hotspot&os=linux&arch=x64&release=latest&heap_size=normal&type=jdk'

    - stage: ☕ jdk.java.net - Java Development Kit builds, from Oracle
      env: JDK=15
      script: source ./install-jdk.sh --verbose --feature ea
    - # stage: ...
      env: JDK=15
      os: osx
      script: source ./install-jdk.sh --verbose --feature ea
    - # stage: ...
      env: JDK=11
      script: source ./install-jdk.sh --feature 11

    - stage: 🍺 adoptopenjdk.net - Eclipse OpenJ9
      env: JDK=11 + OpenJ9
      script: source install-jdk.sh --url 'https://api.adoptopenjdk.net/v2/binary/releases/openjdk11?openjdk_impl=openj9&os=linux&arch=x64&release=latest&heap_size=normal&type=jdk'

    - stage: 🚫 jdk.java.net - Archived OpenJDK General-Availability Releases
      env: JDK=14 🚫
      script: source ./install-jdk.sh --feature 14
    - # stage: ...
      env: JDK=13 🚫
      script: source ./install-jdk.sh --feature 13
    - # stage: ...
      env: JDK=12 🚫
      script: source ./install-jdk.sh --feature 12
    - # stage: ...
      env: JDK=11 🚫
      script: source ./install-jdk.sh --feature 11
    - # stage: ...
      env: JDK=10 🚫
      script: source ./install-jdk.sh --feature 10
    - # stage: ...
      env: JDK=9 🚫
      script: source ./install-jdk.sh --feature 9

    - stage: 🍺 adoptopenjdk.net - HotSpot
      env: JDK=11 + Hotspot
      script: source install-jdk.sh --url 'https://api.adoptopenjdk.net/v2/binary/releases/openjdk11?openjdk_impl=hotspot&os=linux&arch=x64&release=latest&heap_size=normal&type=jdk'
    - # stage: ...
      env: JDK=15 + Hotspot
      script: source install-jdk.sh --url 'https://api.adoptopenjdk.net/v2/binary/releases/openjdk15?openjdk_impl=hotspot&os=linux&arch=x64&release=latest&heap_size=normal&type=jdk'

    - stage: 🍺 adoptopenjdk.net - Eclipse OpenJ9
      env: JDK=11 + OpenJ9
      script: source install-jdk.sh --url 'https://api.adoptopenjdk.net/v2/binary/releases/openjdk11?openjdk_impl=openj9&os=linux&arch=x64&release=latest&heap_size=normal&type=jdk'

addons:
  sonarcloud:
    organization: "nhenneaux"
    token:
      secure: "K7XrobiWi+cBNzbp4hXj5kUKtmPtg1EhnXX6a/l7NG/oTH5yIiGMpOIiAsHNW18GnHbUK9o341d6kvF6S+I9dptP7CULc2Ukk8vnMNeRLB+hO5zEde3XQ5cjWPLsuVnS3N7aPVHaOiwAGsbqvz+9VVQHy1A9HFwPyjzLHf9g3vmzyNQQdpjNJ6zpNKnvezU9U/iH0QOiYZZKc7nxRpESbYdW3ONDAQ5VWsWqqVwm7SGfmYMOkokUfyI75Mc1hFKG5nwtxLNVc7aXgika3x71LMfNuU0LpbWe6eJaTi1kVTia+hFWBZMhNAzd3QAdBmGtULp1I2McfZ97S/PKoOtS/7j8FFYFlw8jvvea0pPx8vJrOYST+/Bj8ZJpftj7lowmzFtGt4OvtIFcwGDed9Vfen5HilCgxz0gXtCIyDm3ZiDHdX2tPEq57SsL5QcvfmVLf4m8w5KTeYYV9yC0mIa+jka7xo3cHFjwokbAvP2ah6xv+Ga4lAdKLDeP+Z4tJAnQFxur+ZM3PF2tSzon+MoViv68jsEYFrhSz2a2NQe5gwMoGYhSjbvpnGpiyjalPhif37BO6CTHYOoYuSB9wIDKIE0pQGX5JHkQivc1QSmklw+SNfq9c3P88zHMuvfNc9SqIkVYb+GJzmecCozF3OKlnBUdzj2Y9IiaT0KPOpSLE/U="

after_script:
  - mvn -B -C verify sonar:sonar -Dsonar.projectKey=nhenneaux_jersey-httpclient-connector
